### PR TITLE
Fix trace mini-map blurry when < 60 spans

### LINKED ISSUE #76: Trace mini-map is blurry when there are only a few spans
Re: https://github.com/uber/jaeger-ui/issues/61#issuecomment-330411067

The mini-map showing the spans is blurry if the trace has only a few spans in it (i.e. < 60 or so).

See attached image.

screen shot 2017-09-20 at 8 25 08 pm

**Steps to reproduce the issue:**
1. View a trace with only a few spans in it.

**Describe the results you received:**

Blurry span mini-map.

**Describe the results you expected:**

Mini-map should not be blurry.

**Additional environment details (Browser, etc.):**

Google Chrome | 60.0.3112.113 (Official Build) (64-bit)
-- | --
Revision | 95c454326a7a3153e984e50a4719924968490717-refs/branch-heads/3112@{#744}
OS | Mac OS X
JavaScript | V8 6.0.286.56

### PR DESCRIPTION
**Pull request by tiffon**
Fix #76 

Before: screen shot 2017-09-20 at 8 25 08 pm

After: screen shot 2017-09-20 at 8 44 45 pm

### CODE REVIEW

File: src/components/TracePage/SpanGraph/render-into-canvas.js [hunk 1]
```diff
@@ -22,17 +22,26 @@
...
   getFillColor: string => string
 ) {
-  // eslint-disable-next-line  no-param-reassign
+  // eslint-disable-next-line no-param-reassign
   canvas.width = CV_WIDTH;
-  // eslint-disable-next-line  no-param-reassign
-  canvas.height = items.length;
+  let itemHeight = 1;
+  if (items.length < MIN_TOTAL_HEIGHT) {
+    // eslint-disable-next-line no-param-reassign
```
Comment (saminzadeh) [inline src/components/TracePage/SpanGraph/render-into-canvas.js]: Maybe just relax this rule in eslint?

Comment (tiffon) [reply src/components/TracePage/SpanGraph/render-into-canvas.js]: I actually like this rule quite a lot.
