### PR TITLE
Fix traceIDs query params clobbering form search

### LINKED ISSUE #82: Jaeger UI carries over traceID URL parameters into future searches
**Description**

When navigating to search page with a traceID in the query parameters, all future searches via the search form only return the specified trace.

**Steps to reproduce the issue:**

1. Go to a page with a traceID search, e.g. http://localhost:3000/search?traceID=abc123
2. Use the search functionality on the left to search for anything
3. Only the trace that we searched for in step 1 shows up instead of the search results
  - The URL is http://localhost:3000/search?end=1506232861152000&limit=20&lookback=1h&maxDuration&minDuration&service=someservervice&start=1506229261152000&traceID=abc123

**Describe the results you received:**

Only the trace specified by the traceID is present in the search results.

**Describe the results you expected:**

Fresh search results. The trace specified by the original traceID query parameter should not be carried into the search results unless it is in the result set.

_T1071845_

### PR DESCRIPTION
**Pull request by tiffon**
Fix #82.

Changed functionality is: traceIDs are ignored when the search form is triggering the search.

### CODE REVIEW

File: src/components/SearchTracePage/TraceSearchForm.js [hunk 1]
```diff
@@ -317,7 +317,6 @@ const mapDispatchToProps = dispatch => {
         tag: tagsToQuery(tags) || undefined,
         minDuration: minDuration || null,
         maxDuration: maxDuration || null,
-        traceID: traceIDsToQuery(traceIDs) || undefined,
```
Comment (yurishkuro) [inline src/components/SearchTracePage/TraceSearchForm.js]: shouldn't this remain? When the search is performed by external URL that contains trace IDs in it, we definitely want them to be used, but when the search is performed via the search form in the UI we don't want the IDs from the previous search to be used

Comment (tiffon) [reply src/components/SearchTracePage/TraceSearchForm.js]: @yurishkuro No, this doesn't need to be here. This is only taking them out of the form submission.

The LOC that handles traceIDs from the URL: [src/components/SearchTracePage/index.js#L72](https://github.com/uber/jaeger-ui/blob/master/src/components/SearchTracePage/index.js#L72)

Comment (saminzadeh) [reply src/components/SearchTracePage/TraceSearchForm.js]: +1
